name: Linters and tests

on: [push, pull_request]

jobs:

  lint_and_test:
    runs-on: ubuntu-latest


    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with mypy and pylint
      run: |
        pip install mypy==0.770 pylint==2.5.0
        ./scripts/linters.sh

    - name: Test with pytest
      run: |
        pip install pytest
        ./scripts/unittests.sh
